// translations.ts
export const translations = {
  english: {
    welcomeBack: "Welcome back,",
    trialActive: "Trial Active",
    subscriptionActive: "Subscription Active",
    expires: "Expires",
    validUntil: "Valid until",
    businessOverview: "Business Overview",
    totalCustomers: "Total Customers",
    servicesDone: "Services Done",
    upcomingServices: "Upcoming Services",
    monthlyRevenue: "Monthly Revenue",
    serviceTypesThisMonth: "Service Types This Month",
    services: "services",
    addNewCustomer: "Add New Customer",
    registerNewCustomer: "Register a new customer and their vehicle details",
    addCustomer: "Add Customer",
    recentCustomers: "Recent Customers",
    viewAll: "View All",
    added: "Added",
    quickInsights: "Quick Insights",
    servicesCompleted: "services completed this month",
    upcomingServicesScheduled: "upcoming services scheduled",
    revenueGenerated: "revenue generated this month",
    loadingDashboard: "Loading dashboard...",
    loadingCustomers: "Loading customers...",
    noCustomers: "No customers found",
    addFirstCustomer: "Add your first customer",
    day: "day",
    days: "days",
    hour: "hour",
    hours: "hours",
    minute: "minute",
    minutes: "minutes",
    ago: "ago",
    searchPlaceholder: "Search by name or phone",
    addVehicle: "Add Vehicle",
    addVehicleFor: "Add Vehicle for",
    noResults: "No customers found",
    // Add any other translations you need
  },
  hindi: {
    welcomeBack: "वापसी पर स्वागत है,",
    trialActive: "ट्रायल सक्रिय",
    subscriptionActive: "सदस्यता सक्रिय",
    expires: "समाप्त",
    validUntil: "तक वैध",
    businessOverview: "व्यवसाय अवलोकन",
    totalCustomers: "कुल ग्राहक",
    servicesDone: "सेवाएं पूर्ण",
    upcomingServices: "आगामी सेवाएं",
    monthlyRevenue: "मासिक आय",
    serviceTypesThisMonth: "इस महीने की सेवा प्रकार",
    services: "सेवाएं",
    addNewCustomer: "नया ग्राहक जोड़ें",
    registerNewCustomer: "एक नए ग्राहक और उनके वाहन का विवरण पंजीकृत करें",
    addCustomer: "ग्राहक जोड़ें",
    recentCustomers: "हाल के ग्राहक",
    viewAll: "सभी देखें",
    added: "जोड़ा गया",
    quickInsights: "त्वरित अंतर्दृष्टि",
    servicesCompleted: "सेवाएं इस महीने पूरी हुईं",
    upcomingServicesScheduled: "आगामी सेवाएं निर्धारित",
    revenueGenerated: "राजस्व इस महीने उत्पन्न हुआ",
    loadingDashboard: "डैशबोर्ड लोड हो रहा है...",
    loadingCustomers: "ग्राहक लोड हो रहे हैं...",
    noCustomers: "कोई ग्राहक नहीं मिले",
    addFirstCustomer: "अपना पहला ग्राहक जोड़ें",
    day: "दिन",
    days: "दिन",
    hour: "घंटा",
    hours: "घंटे",
    minute: "मिनट",
    minutes: "मिनट",
    ago: "पहले",
    searchPlaceholder: "नाम या फोन से खोजें",
    addVehicle: "वाहन जोड़ें",
    addVehicleFor: "के लिए वाहन जोड़ें",
    noResults: "कोई ग्राहक नहीं मिले",
    // Add any other translations you need
  }
};

// You can also export a type for better TypeScript support
export type LanguageKey = keyof typeof translations;
export type TranslationKey = keyof typeof translations.english;