export const translations = {
    english: {
      profile: "Profile",
      services: "services",
      staffManagement: "Staff Management",
      addStaffMember: "Add Staff Member",
      addNewStaff: "Add New Staff",
      email: "Email",
      enterStaffEmail: "Enter staff email",
      phoneNumber: "Phone Number",
      enterPhoneNumber: "Enter 10-digit phone number",
      password: "Password",
      enterPassword: "Enter password (min 6 characters)",
      confirmPassword: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm password",
      addStaff: "Add Staff",
      staffAddedSuccess: "Staff Added Successfully!",
      staffAddedMessage: "The new staff member has been added to your team.",
      ok: "OK",
      error: "Error",
      fillAllDetails: "Please fill all staff details",
      validEmail: "Please enter a valid email address",
      validPhone: "Please enter a valid 10-digit phone number",
      passwordLength: "Password must be at least 6 characters long",
      passwordsDontMatch: "Passwords do not match",
      failedAddStaff: "Failed to add staff member",
      notProvided: "Not provided",
      loadingProfile: "Loading profile data...",
      authenticationError: "Authentication required. Please login again.",
      reminderPeriod: "Reminder Period",
      reminderSettings: "Reminder Settings",
      privateVehicles: "Private Vehicles",
      taxiVehicles: "Taxi Vehicles",
      months: "months",
      saveSettings: "Save Settings",
      settingsSaved: "Settings Saved",
      settingsSavedMessage: "Reminder settings have been updated successfully",
      // New delete related translations
      deleteStaff: "Delete Staff",
      confirmDelete: "Confirm Delete",
      deleteStaffConfirm: "Are you sure you want to delete this staff member?",
      deleteStaffWarning: "This action cannot be undone.",
      cancel: "Cancel",
      delete: "Delete",
      staffDeletedSuccess: "Staff Deleted Successfully!",
      staffDeletedMessage: "The staff member has been removed from your team.",
      failedDeleteStaff: "Failed to delete staff member",
      cannotDeleteAdmin: "Cannot delete service center admin",
    },
    hindi: {
      profile: "प्रोफाइल",
      services: "सेवाएं",
      staffManagement: "स्टाफ प्रबंधन",
      addStaffMember: "स्टाफ सदस्य जोड़ें",
      addNewStaff: "नया स्टाफ जोड़ें",
      email: "ईमेल",
      enterStaffEmail: "स्टाफ ईमेल दर्ज करें",
      phoneNumber: "फोन नंबर",
      enterPhoneNumber: "10-अंकीय फोन नंबर दर्ज करें",
      password: "पासवर्ड",
      enterPassword: "पासवर्ड दर्ज करें (न्यूनतम 6 अक्षर)",
      confirmPassword: "पासवर्ड की पुष्टि करें",
      confirmPasswordPlaceholder: "पासवर्ड की पुष्टि करें",
      addStaff: "स्टाफ जोड़ें",
      staffAddedSuccess: "स्टाफ सफलतापूर्वक जोड़ा गया!",
      staffAddedMessage: "नया स्टाफ सदस्य आपकी टीम में जोड़ दिया गया है।",
      ok: "ठीक है",
      error: "त्रुटि",
      fillAllDetails: "कृपया सभी स्टाफ विवरण भरें",
      validEmail: "कृपया एक वैध ईमेल पता दर्ज करें",
      validPhone: "कृपया एक वैध 10-अंकीय फोन नंबर दर्ज करें",
      passwordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
      passwordsDontMatch: "पासवर्ड मेल नहीं खाते",
      failedAddStaff: "स्टाफ सदस्य जोड़ने में विफल",
      notProvided: "प्रदान नहीं किया गया",
      loadingProfile: "प्रोफाइल डेटा लोड हो रहा है...",
      authenticationError: "प्रमाणीकरण आवश्यक है। कृपया फिर से लॉगिन करें।",
      reminderPeriod: "अनुस्मारक अवधि",
      reminderSettings: "अनुस्मारक सेटिंग्स",
      privateVehicles: "निजी वाहन",
      taxiVehicles: "टैक्सी वाहन",
      months: "महीने",
      saveSettings: "सेटिंग्स सहेजें",
      settingsSaved: "सेटिंग्स सहेजे गए",
      settingsSavedMessage: "अनुस्मारक सेटिंग्स सफलतापूर्वक अपडेट की गई हैं",
      // New delete related translations
      deleteStaff: "स्टाफ हटाएं",
      confirmDelete: "हटाने की पुष्टि करें",
      deleteStaffConfirm: "क्या आप वाकई इस स्टाफ सदस्य को हटाना चाहते हैं?",
      deleteStaffWarning: "यह क्रिया पूर्ववत नहीं की जा सकती।",
      cancel: "रद्द करें",
      delete: "हटाएं",
      staffDeletedSuccess: "स्टाफ सफलतापूर्वक हटा दिया गया!",
      staffDeletedMessage: "स्टाफ सदस्य को आपकी टीम से हटा दिया गया है।",
      failedDeleteStaff: "स्टाफ सदस्य हटाने में विफल",
      cannotDeleteAdmin: "सेवा केंद्र व्यवस्थापक को हटाया नहीं जा सकता",
    }
  };

export type LanguageKey = keyof typeof translations;
export type TranslationKey = keyof typeof translations.english;