// HomeStyles.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5faff',
  },
  scrollContainer: {
    paddingTop: 120,
    paddingBottom: 20,
    paddingHorizontal: 16,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    paddingTop: 50,
    backgroundColor: '#0052cc',
    borderBottomWidth: 1,
    borderBottomColor: '#003087',
    minHeight: 100,
  },
  sidebarToggle: {
    padding: 8,
    marginRight: 16,
  },
  headerContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  headerMainInfo: {
    alignItems: 'flex-end',
    marginRight: 16,
  },
  shopName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'right',
  },
  subscriptionStatus: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    marginTop: 4,
  },
  trialIndicator: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
    backgroundColor: '#003087',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginBottom: 4,
  },
  subscriptionIndicator: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
    backgroundColor: '#003087',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginBottom: 4,
  },
  expiryText: {
    fontSize: 11,
    color: '#b3ccff',
    textAlign: 'right',
  },
  notificationIcon: {
    padding: 6,
  },
  section: {
    marginTop: 24,
    marginBottom: 28,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 16,
  },
  searchContainer: {
    marginBottom: 16,
  },
  searchTypeToggle: {
    flexDirection: 'row',
    backgroundColor: '#e6f0fa',
    borderRadius: 8,
    padding: 4,
    marginBottom: 12,
  },
  searchTypeButton: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: 'center',
  },
  activeSearchType: {
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  searchTypeText: {
    fontSize: 14,
    color: '#0052cc',
    fontWeight: '500',
  },
  activeSearchTypeText: {
    color: '#003087',
    fontWeight: '600',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#0052cc',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#000000',
    paddingVertical: 8,
    paddingHorizontal: 0,
  },
  clearIcon: {
    padding: 8,
    backgroundColor: '#e6f0fa',
    borderRadius: 16,
  },
  addCustomerIconButton: {
    padding: 8,
    backgroundColor: '#0052cc',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  inlineAddCustomerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0052cc',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    marginTop: 12,
    alignSelf: 'flex-start',
  },
  inlineAddCustomerButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 15,
    marginLeft: 4,
  },
  addCustomerContainer: {
    marginBottom: 16,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  customersContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    overflow: 'hidden',
    minHeight: 100,
  },
  customerCardWrapper: {
    marginBottom: 12,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  customerCard: {
    backgroundColor: '#ffffff',
    flexDirection: 'column',
    padding: 16,
  },
  expandedCustomerCard: {
    minHeight: 200,
  },
  customerTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  customerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0052cc',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  avatarText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  customerInfo: {
    flex: 1,
    marginRight: 16,
  },
  customerName: {
    fontSize: 12,
    color: '#000000',
    fontWeight: '400',
    marginBottom: 2,
  },
  boldPhoneNumber: {
    fontSize: 15,
    color: '#000000',
    fontWeight: '700',
    marginBottom: 4,
  },
  vehicleSearchInfo: {
    marginBottom: 4,
  },
  vehicleNumberText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
    backgroundColor: '#003087',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginBottom: 2,
  },
  vehicleCount: {
    fontSize: 14,
    color: '#000000',
    marginBottom: 2,
  },
  addedTime: {
    fontSize: 12,
    color: '#000000',
  },
  customerActions: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  actionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#003087',
    justifyContent: 'center',
    alignItems: 'center',
  },
  expandIcon: {
    padding: 4,
  },
  expandedContent: {
    marginTop: 8,
  },
  divider: {
    height: 1,
    backgroundColor: '#b3ccff',
    marginBottom: 12,
  },
  vehiclesSection: {
    marginBottom: 16,
  },
  vehiclesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 8,
  },
  vehicleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    padding: 8,
    backgroundColor: '#f8fafc',
    borderRadius: 6,
  },
  vehicleText: {
    fontSize: 14,
    color: '#000000',
    marginLeft: 8,
  },
  noVehiclesText: {
    fontSize: 14,
    color: '#000000',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 12,
  },
  customerActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    flex: 1,
  },
  addVehicleButton: {
    backgroundColor: '#0052cc',
  },
  nextButton: {
    backgroundColor: '#003087',
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 12,
    marginLeft: 4,
  },
  vehiclesLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  loadingContainer: {
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  loadingText: {
    marginLeft: 10,
    color: '#000000',
  },
  emptyContainer: {
    padding: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 10,
    color: '#000000',
    fontSize: 16,
    marginBottom: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 82, 204, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    width: '90%',
    maxHeight: '80%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#b3ccff',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#000000',
    flex: 1,
  },
  closeButton: {
    padding: 4,
  },
  selectedCustomerContainer: {
    flex: 1,
  },
  selectedCustomerHeader: {
    marginBottom: 16,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  backButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 6,
  },
  customerFormCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  customerFormAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#0052cc',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  formHeaderInfo: {
    flex: 1,
  },
  formCustomerName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 4,
  },
  formCustomerPhone: {
    fontSize: 16,
    color: '#000000',
    fontWeight: '600',
  },
  callButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#003087',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formDivider: {
    height: 1,
    backgroundColor: '#b3ccff',
    marginVertical: 20,
  },
  formSection: {
    marginBottom: 20,
  },
  formSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000000',
    marginBottom: 16,
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    marginBottom: 8,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
    width: 80,
    marginRight: 16,
  },
  formValue: {
    fontSize: 14,
    color: '#000000',
    flex: 1,
  },
  vehiclesSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  addVehicleIconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#003087',
    justifyContent: 'center',
    alignItems: 'center',
  },
  vehiclesList: {
    maxHeight: 200,
  },
  vehicleFormItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#0052cc',
  },
  vehicleFormInfo: {
    flex: 1,
    marginLeft: 12,
  },
  vehicleFormName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    marginBottom: 4,
  },
  vehicleFormDetails: {
    fontSize: 14,
    color: '#000000',
  },
  noVehiclesContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  noVehiclesFormText: {
    fontSize: 16,
    color: '#000000',
    marginTop: 12,
    marginBottom: 20,
    textAlign: 'center',
  },
  addFirstVehicleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0052cc',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  addFirstVehicleText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 6,
  },
  formActions: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#b3ccff',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 10,
    width: '100%',
  },
  addServiceFormButton: {
    backgroundColor: '#003087',
  },
  actionButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
    marginLeft: 6,
  },
  banner: {
    marginTop: 10,
  },
  // Add these styles to your HomeStyles.ts file
suggestionsContainer: {
  backgroundColor: '#ffffff',
  borderWidth: 1,
  borderColor: '#b3ccff',
  borderTopWidth: 0,
  borderBottomLeftRadius: 8,
  borderBottomRightRadius: 8,
  marginTop: -4,
  zIndex: 1000,
  elevation: 5
}
});